###########################################################################
#                REQUISIÇÕES PARA OPERAÇÕES COM INSTITUTOS                #
###########################################################################

### Apresenta lista de Institutos:
GET http://localhost:8072/instituto/ HTTP/1.1
content-type: application/json

### Cadastra instituto:
POST http://localhost:8072/instituto/ HTTP/1.1
content-type: application/json

{
    "nome": "Faculdade Professor Miguel Ângelo da Silva Santos",
    "acronimo": "FEMASS"
}

### Apaga o instituto id 1:
GET http://localhost:8080/instituto/1 HTTP/1.1

### Pesquisa o instituto pelo o nome em qualquer parte
GET http://localhost:8080/instituto/nome/universidade HTTP/1.1

### Pesquisa o instituto pelo o acronimo em qualquer parte 
GET http://localhost:8080/instituto/acronimo/UF HTTP/1.1


///Pesquisador

###  Pegar todos os pesquisadores que estão cadastrados no banco de dados 
GET http://localhost:8072/pesquisador/ HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
GET http://localhost:8072/pesquisador/add/0263660448893625/instituto/2 HTTP/1.1

### Procura um pesquisador baseado no identificador, porém é necessário que esteja cadastrado no bd 
GET http://localhost:8072/pesquisador/0024160866319507 HTTP/1.1

### Excluir um pesquisador do banco de dados 
GET http://localhost:8072/pesquisador/excluir/2602 HTTP/1.1