###########################################################################
#                REQUISIÇÕES PARA OPERAÇÕES COM INSTITUTOS                #
###########################################################################

### Cadastra instituto:
POST http://localhost:8080/instituto/ HTTP/1.1
content-type: application/json

{
    "nome": "Faculdade Professor Miguel Ângelo da Silva Santos",
    "acronimo": "FEMASS"
}

### Cadastra instituto:
POST http://localhost:8080/instituto/ HTTP/1.1
content-type: application/json

{
    "nome": "Universidade Federal do Rio de Janeiro",
    "acronimo": "UFRJ"
}

### Cadastra instituto:
POST http://localhost:8080/instituto/ HTTP/1.1
content-type: application/json

{
    "nome": "Universidade Federal Fluminense",
    "acronimo": "UFF"
}

### Cadastra instituto:
POST http://localhost:8080/instituto/ HTTP/1.1
content-type: application/json

{
    "nome": "Faculdade Católica Salesiana",
    "acronimo": "SALESIANA"
}

### Cadastra instituto:
POST http://localhost:8080/instituto/ HTTP/1.1
content-type: application/json

{
    "nome": "Universidade Estácio de Sá",
    "acronimo": "ESTÁCIO"
}

### Cadastra instituto:
POST http://localhost:8080/instituto/ HTTP/1.1
content-type: application/json

{
    "nome": "Instituto de Teste",
    "acronimo": "TESTE"
}

### Apaga o instituto id 6:
DELETE http://localhost:8080/instituto/6 HTTP/1.1

### Apresenta uma página de Institutos:
GET http://localhost:8080/instituto HTTP/1.1
content-type: application/json

###  Listar os institutos de forma paginada:
GET http://localhost:8080/instituto?page=0&size=1 HTTP/1.1

###  Listar os institutos de forma lista:
GET http://localhost:8080/instituto/list HTTP/1.1

### Pesquisa o instituto pelo o nome em qualquer parte
GET http://localhost:8080/instituto?nome=federal HTTP/1.1

### Pesquisa o instituto pelo o acronimo em qualquer parte 
GET http://localhost:8080/instituto?acronimo=UFF HTTP/1.1

### Pesquisa o instituto pelo o acronimo em qualquer parte 
GET http://localhost:8080/instituto?nomeacronimo=UFF HTTP/1.1

### Retorna a quantidade total de institutos
GET http://localhost:8080/instituto/count HTTP/1.1

###########################################################################
#                REQUISIÇÕES PARA OPERAÇÕES COM PESQUISADOR               #
#                  INSERÇÃO DE TODOS OS 29 PESQUISADORES                  #
###########################################################################

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0023809873085852/instituto/1 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0024160866319507/instituto/1 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0028876341054325/instituto/1 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0047810385809553/instituto/1 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0053636364868790/instituto/1 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0066576690749759/instituto/1 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0082487176176434/instituto/2 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0110662125645595/instituto/2 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0112621452737067/instituto/2 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0161902355523060/instituto/2 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0194631586754988/instituto/2 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0235080730138338/instituto/2 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0263660448893625/instituto/3 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0329773854976808/instituto/3 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0348923590713594/instituto/3 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0485361810192703/instituto/3 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0491984479926888/instituto/3 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0549723858731158/instituto/3 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0559800226477492/instituto/4 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0600549075776976/instituto/4 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0604237405440586/instituto/4 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0658455060876989/instituto/4 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0659726776097432/instituto/4 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0676650998291996/instituto/4 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0692400140993944/instituto/5 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0743793296062293/instituto/5 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0770145420421898/instituto/5 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0781779929562675/instituto/5 HTTP/1.1

### Adicionar um pesquisador com instituto no banco de dados 
POST http://localhost:8080/pesquisador/add/0814717344017544/instituto/5 HTTP/1.1

###########################################################################
#                REQUISIÇÕES PARA OPERAÇÕES COM PESQUISADOR               #
###########################################################################

###  Listar os pesquisadores de forma paginada 
GET http://localhost:8080/pesquisador?page=0&size=5 HTTP/1.1

###  Listar os pesquisadores que estão no instituto 1 em forma de lista
GET http://localhost:8080/pesquisador/list?instituto=1 HTTP/1.1

### Pesquisa o pesquisador pelo o nome em qualquer parte
GET http://localhost:8080/pesquisador?nome=Salvador HTTP/1.1

### Procura um pesquisador baseado no identificador, porém é necessário que esteja cadastrado no bd 
GET http://localhost:8080/pesquisador?identificador=0814717344017544 HTTP/1.1

###  Pegar todos os pesquisadores que estão no instituto 1: 
GET http://localhost:8080/pesquisador?instituto=1 HTTP/1.1

### Excluir um pesquisador do banco de dados
DELETE http://localhost:8080/pesquisador/excluir/0770145420421898 HTTP/1.1 

### Retorna a quantidade total de pesquisadores
GET http://localhost:8080/pesquisador/count HTTP/1.1

###########################################################################
#                  REQUISIÇÕES PARA OPERAÇÕES COM PRODUÇÃO                #
###########################################################################

###  Listar as Produções de forma paginada 
GET http://localhost:8080/producao?page=0&size=10 HTTP/1.1

### Teste de produção 
GET http://localhost:8080/producao?anoInicio=2004&anoFim=2022&instituto=Estácio&pesquisador=Gestinari&tipoProducao=Trabalho em Evento HTTP/1.1

### Teste de produção 
GET http://localhost:8080/producao?anoInicio=2000&anoFim=2000&page=0&size=10 HTTP/1.1

### Pesquisa as produções pelo ano
GET http://localhost:8080/producao?ano=2002 HTTP/1.1

### Pesquisa as produções pelo instituto
GET http://localhost:8080/producao?instituto=Faculdade Católica Salesiana HTTP/1.1

### Pesquisa as produções pelo pesquisador
GET http://localhost:8080/producao?pesquisador=Rute Ramos da Silva Costa HTTP/1.1

### Pesquisa as produções pelo tipo de produção
GET http://localhost:8080/producao?tipoProducao=Trabalho em Evento HTTP/1.1

### Retorna a quantidade total de produções
GET http://localhost:8080/producao/count HTTP/1.1

### Retorna uma lista com a quantidade total de produções a cada ano
GET http://localhost:8080/producao/countTotalProducoesPorAno?dataInicio=2000&dataFim=2005 HTTP/1.1

### Retorna uma lista com a quantidade total de produções de cada tipo
GET http://localhost:8080/producao/countTotalProducoesPorTipo HTTP/1.1

###########################################################################
#                   REQUISIÇÕES PARA OPERAÇÕES COM AUTOR                  #
###########################################################################

### Verifica se um autor já está cadastrado
GET http://localhost:8080/autor/autorExiste/Lï¿½sia Mï¿½nica de Souza Gestinari HTTP/1.1

### Pesquisa o ator pelo nome em qualquer parte
GET http://localhost:8080/autor/nome/Lï¿½sia HTTP/1.1

###########################################################################
#            REQUISIÇÕES PARA OPERAÇÕES COM TIPO DE PRODUÇÃO              #
###########################################################################

### Retorna uma página contendo os tipos de produção existentes no enum
GET http://localhost:8080/tipoProducao HTTP/1.1

###########################################################################
#            REQUISIÇÕES PARA OPERAÇÕES COM TIPO DE VERTICE               #
###########################################################################

### Retorna uma página contendo os tipos de produção existentes no enum
GET http://localhost:8080/tipoVertice HTTP/1.1

###########################################################################
#             REQUISIÇÕES PARA OPERAÇÕES COM GRAFO                        #
###########################################################################

### Vertices de todos os pesquisadores
GET http://localhost:8080/pesquisador/cytoscapejs HTTP/1.1

### Vertices de todos os institutos
GET http://localhost:8080/instituto/cytoscapejs HTTP/1.1

### Aresta de Pesquisador para Pesquisador
GET http://localhost:8080/producao/cytoscapejsPesquisador HTTP/1.1

### Aresta de Instituto para Instituto
GET http://localhost:8080/producao/cytoscapejsInstituto HTTP/1.1

### FALTA IMPLEMENTAR O FILTRO DINÂMICO
### Filtro Dinamico para Geração do Grafo
GET http://localhost:8080/producao/filtroDinamicoGrafo?pesquisadores=0235080730138338&tipoProducao=Livro&tipoVertice=Pesquisador HTTP/1.1